/**
 * One-off helper: append TV stubs to library.json (idempotent by id).
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const LIBRARY_PATH = join(__dirname, '..', 'src', 'data', 'library.json')

/** [id, searchQuery, displayTitle?, tmdbId?] */
const NEW_SHOWS = [
  ['arrested-development', 'Arrested Development'],
  ['ozark', 'Ozark'],
  ['best-medicine', 'Best Medicine'],
  ['extras', 'Extras'],
  ['the-office-uk', 'The Office UK'],
  ['the-office-us', 'The Office US'],
  ['parks-and-recreation', 'Parks and Recreation'],
  ['derek', 'Derek'],
  ['taskmaster', 'Taskmaster'],
  ['flaked', 'Flaked'],
  ['upper-middle-bogan', 'Upper Middle Bogan'],
  ['colin-from-accounts', 'Colin From Accounts'],
  ['platonic', 'Platonic'],
  ['the-studio', 'The Studio'],
  ['foundation', 'Foundation'],
  ['see', 'See'],
  ['legends', 'Legends', 'Legends', 262280],
  ['outlaws', 'The Outlaws', 'The Outlaws', 136044],
  ['detroiters', 'Detroiters'],
  ['i-think-you-should-leave', 'I Think You Should Leave with Tim Robinson'],
  ['key-and-peele', 'Key & Peele'],
  ['the-handmaids-tale', "The Handmaid's Tale"],
  ['resident-alien', 'Resident Alien'],
  ['the-testaments', 'The Testaments'],
  ['mobland', 'MobLand'],
  ['boardwalk-empire', 'Boardwalk Empire'],
  ['battlestar-galactica', 'Battlestar Galactica', 'Battlestar Galactica (2004)', 1972],
  ['true-detective', 'True Detective'],
  ['the-white-lotus', 'The White Lotus'],
  ['game-of-thrones', 'Game of Thrones'],
  ['a-knight-of-the-seven-kingdoms', 'A Knight of the Seven Kingdoms'],
  ['house-of-the-dragon', 'House of the Dragon'],
  ['frayed', 'Frayed'],
  ['this-way-up', 'This Way Up'],
  ['game-face', 'GameFace', 'GameFace', 88471],
  ['fleabag', 'Fleabag'],
  ['peacemaker', 'Peacemaker'],
  ['boy-swallows-universe', 'Boy Swallows Universe'],
  ['flight-of-the-conchords', 'Flight of the Conchords'],
  ['alice-and-steve', 'Alice and Steve'],
  ['what-we-do-in-the-shadows', 'What We Do in the Shadows'],
  ['bad-monkey', 'Bad Monkey'],
  ['star-city', 'Star City'],
  ['maximum-pleasure-guaranteed', 'Maximum Pleasure Guaranteed'],
  ['invincible', 'Invincible'],
  ['archer', 'Archer'],
  ['narcos', 'Narcos'],
  ['narcos-mexico', 'Narcos: Mexico'],
  ['queen-of-the-south', 'Queen of the South'],
  ['versailles', 'Versailles'],
  ['masters-of-the-air', 'Masters of the Air'],
  ['half-man', 'Half Man'],
  ['bodkin', 'Bodkin'],
  ['the-last-man-on-earth', 'The Last Man on Earth'],
  ['3-body-problem', '3 Body Problem'],
  ['the-expanse', 'The Expanse'],
  ['patriot', 'Patriot', 'Patriot', 64396],
  ['katla', 'Katla'],
  ['dark', 'Dark', 'Dark', 70523],
  ['1923', '1923'],
  ['1883', '1883'],
  ['frontier', 'Frontier', 'Frontier', 67744],
  ['black-sails', 'Black Sails'],
  ['californication', 'Californication'],
  ['weeds', 'Weeds'],
  ['entourage', 'Entourage'],
  ['better-call-saul', 'Better Call Saul'],
  ['breaking-bad', 'Breaking Bad'],
  ['sons-of-anarchy', 'Sons of Anarchy'],
  ['babylon-berlin', 'Babylon Berlin'],
  ['fargo', 'Fargo'],
  ['the-big-bang-theory', 'The Big Bang Theory'],
  ['the-mandalorian', 'The Mandalorian'],
  ['wandavision', 'WandaVision'],
  ['obi-wan-kenobi', 'Obi-Wan Kenobi'],
  ['andor', 'Andor'],
  ['after-the-flood', 'After the Flood'],
  ['shetland', 'Shetland'],
  ['task', 'Task', 'Task', 228305],
  ['broadchurch', 'Broadchurch'],
  ['mare-of-easttown', 'Mare of Easttown'],
  ['killing-eve', 'Killing Eve'],
  ['the-night-manager', 'The Night Manager'],
  ['slow-horses', 'Slow Horses'],
  ['the-killing', 'The Killing', 'The Killing', 34415],
  ['hanna', 'Hanna'],
  ['30-rock', '30 Rock'],
  ['afterlife', 'After Life'],
  ['ahsoka', 'Ahsoka'],
  ['altered-carbon', 'Altered Carbon'],
  ['all-the-light-we-cannot-see', 'All the Light We Cannot See'],
  ['american-primeval', 'American Primeval'],
  ['angel', 'Angel', 'Angel', 2426],
  ['archive-81', 'Archive 81'],
  ['inside-amy-schumer', 'Inside Amy Schumer', 'Inside Amy Schumer', 47562],
  ['atypical', 'Atypical'],
  ['atlanta', 'Atlanta'],
  ['bad-sisters', 'Bad Sisters'],
  ['band-of-brothers', 'Band of Brothers'],
  ['barbarians', 'Barbarians', 'Barbarians', 93785],
  ['barry', 'Barry'],
  ['beef', 'Beef'],
  ['better-than-us', 'Better Than Us'],
  ['big-little-lies', 'Big Little Lies'],
  ['big-love', 'Big Love'],
  ['black-doves', 'Black Doves'],
  ['black-bird', 'Black Bird', 'Black Bird', 155537],
  ['blockbuster', 'Blockbuster', 'Blockbuster', 201874],
  ['bloodline', 'Bloodline'],
  ['bobs-burgers', "Bob's Burgers"],
  ['bodies', 'Bodies', 'Bodies', 233629],
  ['bodyguard', 'Bodyguard', 'Bodyguard', 80307],
  ['the-book-of-boba-fett', 'The Book of Boba Fett'],
  ['the-boondocks', 'The Boondocks'],
  ['bored-to-death', 'Bored to Death'],
  ['borgen', 'Borgen'],
  ['britannia', 'Britannia'],
  ['broad-city', 'Broad City'],
  ['workaholics', 'Workaholics'],
  ['dune-prophecy', 'Dune: Prophecy'],
  ['the-witcher', 'The Witcher'],
  ['the-pacific', 'The Pacific'],
  ['alice-in-borderland', 'Alice in Borderland'],
  ['squid-game', 'Squid Game'],
  ['stranger-things', 'Stranger Things'],
  ['fallout', 'Fallout'],
  ['the-simpsons', 'The Simpsons'],
  ['secret-city', 'Secret City', 'Secret City', 66357],
  ['chad', 'Chad', 'Chad', 89578],
  ['community', 'Community'],
  ['chernobyl', 'Chernobyl', 'Chernobyl', 87108],
  ['cunk-on-earth', 'Cunk on Earth', 'Cunk on Earth', 79063],
  ['dark-matter', 'Dark Matter', 'Dark Matter', 196322],
  ['dave', 'Dave'],
  ['deadwood', 'Deadwood'],
  ['derry-girls', 'Derry Girls'],
  ['the-detectorists', 'The Detectorists'],
  ['dexter', 'Dexter', 'Dexter', 1405],
  ['downton-abbey', 'Downton Abbey'],
  ['el-chapo', 'El Chapo', 'El Chapo', 71411],
  ['fauda', 'Fauda', 'Fauda', 69557],
  ['friday-night-lights', 'Friday Night Lights'],
  ['friends', 'Friends'],
  ['gangs-of-london', 'Gangs of London'],
  ['gangs-of-oslo', 'Gangs of Oslo', 'Gangs of Oslo', 216604],
  ['glow', 'GLOW'],
  ['ghosts', 'Ghosts (US)', 'Ghosts', 126027],
  ['get-shorty', 'Get Shorty'],
  ['ghosts-bbc', 'Ghosts (BBC)', 'Ghosts BBC', 17174],
  ['godless', 'Godless', 'Godless', 73467],
]

const emptyCached = {
  title: null,
  overview: null,
  posterPath: null,
  backdropPath: null,
  genreNames: [],
  firstAirYear: null,
  topCast: [],
  streamingProviders: [],
}

function stub(id, title, searchQuery = title, tmdbId = null) {
  return {
    id,
    kind: 'tv',
    external: { tmdbId, searchQuery },
    cached: { ...emptyCached },
    mine: {
      title,
      status: 'watching',
      rating: null,
      notes: '',
      tags: [],
    },
  }
}

const library = JSON.parse(readFileSync(LIBRARY_PATH, 'utf8'))
const ids = new Set(library.items.map((i) => i.id))
let added = 0
for (const row of NEW_SHOWS) {
  const [id, searchQuery, title = searchQuery, tmdbId = null] = row
  if (ids.has(id)) continue
  library.items.push(stub(id, title, searchQuery, tmdbId))
  ids.add(id)
  added++
}
writeFileSync(LIBRARY_PATH, `${JSON.stringify(library, null, 2)}\n`, 'utf8')
console.log(`Added ${added} show(s) to ${LIBRARY_PATH}`)
